[project]
authors = [ { name = "Philip White" } ]
dependencies = [
    "k_means_constrained",
    "scipy"
]
name = "jnp-org"
license = { file = "LICENSE" }
readme = "README.md"
version = "2022.12.29"
